name: Run Discord Bot

on: 
  push:
    branches:
      - main  # Ejecuta el flujo de trabajo cuando haya un push a la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # El entorno donde se ejecutará el bot

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3  # Clona tu repositorio en el entorno de GitHub Actions

      - name: Configurar Python
        uses: actions/setup-python@v3  # Configura el entorno de Python
        with:
          python-version: '3.9'  # Especifica la versión de Python que deseas usar (ajústalo si necesitas otra)

      - name: Instalar dependencias
        run: pip install -r requirements.txt  # Instala las dependencias de tu bot desde requirements.txt

      - name: Crear archivo .env
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env  # Crea el archivo .env con el token de Discord
          echo "PANDASCORE_TOKEN=${{ secrets.PANDASCORE_TOKEN }}" >> .env  # Crea el archivo .env con el token de PandaScore

      - name: Ejecutar el bot
        run: python bot.py  # Ejecuta el bot de Discord
